services:
  - type: web
    name: titanbot-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python entrypoint.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MANAGER_CHAT_ID
        sync: false
